# ==== settings.yml ====

# tags
TAGS:
    FAMILY: tag36h11
    IDS: [0, 1, 2, 3]
ALPHA: 0.5

# AOIs; xy - 0 means center, 1 means edge; horiz/vert - 0 means left/top, 1 means right/bottom
AOIS:
  - name: left
    tag_upleft:
      id: 0
      xy: [0, 0]
    tag_upright:
      id: 1
      xy: [0, 0]
    tag_botleft:
      id: 2
      xy: [0, 0]
    tag_botright:
      id: 3
      xy: [0, 0]
    horiz: [0.06, 0.49]
    vert: [-0.08, 1.08]
    color_bgr: [0, 255, 0]
  - name: right
    tag_upleft:
      id: 0
      xy: [0, 0]
    tag_upright:
      id: 1
      xy: [0, 0]
    tag_botleft:
      id: 2
      xy: [0, 0]
    tag_botright:
      id: 3
      xy: [0, 0]
    horiz: [0.5, 0.94]
    vert: [-0.08, 1.08]
    color_bgr: [255, 0, 0]
  - name: person
    tag_upleft:
      id: 0
      xy: [0, 0]
    tag_upright:
      id: 1
      xy: [0, 0]
    tag_botleft:
      id: 2
      xy: [0, 0]
    tag_botright:
      id: 3
      xy: [0, 0]
    horiz: [0.065, 0.24]
    vert: [0.1, 1]
    color_bgr: [100, 0, 100]

# files
PATH_VID: C:/Users/User/Desktop/pendrive_28052024/Pupil_data/2024_06_19/024/ #video/ # 0 for webcam
FILE: world.mp4
PATH_GAZE: C:/Users/User/Desktop/pendrive_28052024/Pupil_data/2024_06_19/024/exports/000/ #gaze/
FILE_GAZE: gaze_positions.csv
TABLE_GAZE: gaze_table
FRAME_START: 5050 #450
FRAME_STOP: 5900 #9400