# ==== settings.yml ====

# tags
TAGS:
    FAMILY: tag36h11
    IDS: [20,17,22,19,23,18]
    CORNERS: 
        20: 0
        17: 3
        22: 0.5
        19: 1.5
        23: 1
        18: 0
X_CORRECT: 0
Y_CORRECT: 0.25
COORD:
    0.5: [0,1]
    1.5: [0,3]
ALPHA: 0.5

# files
PATH_VID: 0 #C:/Users/User/Desktop/pendrive_28052024/Pupil_data/2024_06_19/024/ #video/ # 0 for webcam
FILE: world.mp4
PATH_GAZE: gaze/
FILE_GAZE: gaze_positions.csv
TABLE_GAZE: gaze_table
FRAME_START: 0
FRAME_STOP: 100 #null